# Generated by Django 4.1 on 2022-10-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_list',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('product_type', models.CharField(max_length=25)),
                ('image', models.ImageField(blank=True, upload_to='image')),
            ],
        ),
        migrations.RemoveField(
            model_name='cust_delivered_items',
            name='cust_id',
        ),
        migrations.RemoveField(
            model_name='cust_delivered_items',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='delivery_person',
            name='emp_id',
        ),
        migrations.RemoveField(
            model_name='delivery_person',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='emp_salary',
            name='delivery_id',
        ),
        migrations.RemoveField(
            model_name='return_list',
            name='cust_id',
        ),
        migrations.RemoveField(
            model_name='return_list',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='return_list',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='pickup_id',
        ),
        migrations.RemoveField(
            model_name='total_delivered_items',
            name='emp_id',
        ),
        migrations.RemoveField(
            model_name='total_delivered_items',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='order_list',
            name='customer_id',
        ),
        migrations.DeleteModel(
            name='cust_cart_list',
        ),
        migrations.DeleteModel(
            name='Cust_delivered_items',
        ),
        migrations.DeleteModel(
            name='delivery_person',
        ),
        migrations.DeleteModel(
            name='Emp_salary',
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
        migrations.DeleteModel(
            name='pickup',
        ),
        migrations.DeleteModel(
            name='return_list',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
        migrations.DeleteModel(
            name='Total_delivered_items',
        ),
    ]
