# Generated by Django 4.1 on 2022-10-17 11:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0007_order_list_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_list',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
