# Generated by Django 4.1 on 2022-11-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0010_alter_products_details_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_list',
            name='cart',
            field=models.ManyToManyField(through='ecom_app.cart_details', to='ecom_app.products_details'),
        ),
    ]
