# Generated by Django 4.1 on 2022-11-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0012_cart_details_is_cancel'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_list',
            name='cancel_status',
            field=models.BooleanField(default=False),
        ),
    ]
