# Generated by Django 4.1 on 2022-10-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0002_cart_details_amounts_cart_details_price_of_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_details',
            name='amounts',
            field=models.FloatField(null=True),
        ),
    ]
