# Generated by Django 4.1 on 2022-10-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0006_alter_order_list_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_list',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
